import Firebase
import FirebaseFirestoreSwift


// Define the ChatMessage model for representing chat messages in the app.
struct ChatMessage: Identifiable, Codable {
    @DocumentID var id: String? // Unique identifier for the message, auto-generated by Firestore.
    var fullname: String?       // Optional: The full name of the sender.
    var senderId: String        // ID of the user who sent the message.
    var receiverId: String      // ID of the user who is supposed to receive the message.
    var content: String         // The actual text content of the message.
    @ServerTimestamp var timestamp: Timestamp? // Timestamp when the message was sent, managed by Firestore.

    // Computed property to check if the current user is the sender of the message.
    var isCurrentUser: Bool {
        return Auth.auth().currentUser?.uid == senderId
    }

    // CodingKeys enum to map the struct properties to the corresponding Firestore document fields.
    enum CodingKeys: String, CodingKey {
        case id
        case fullname
        case senderId
        case receiverId
        case content
        case timestamp
    }
}
